### ISSUE TITLE
Bucket List

### ISSUE THREAD

**Issue by kenos1** [HasangerGames/suroi-wiki#18]
- [x] Image generation for player holding weapons, buildings, etc. (Use SVG/Canvas)
- [x] Refactor image tabs (more flexible)
- [x] Backpacks
- [ ] Building viewer
- [x] Front page redesign (make it look more :sunglasses:)
- [x] CI pipeline for deploying (no waiting for Henry to update)

## Far far future
- [ ] Sveltekit migration
- [ ] Unocss migration

**Comment by sawq375** [comment]
I have a question. How does articles work? like when you make them how do they get to the website and get posted

**Comment by kenos1** [comment]
> I have a question. How does articles work? like when you make them how do they get to the website and get posted

Hasanger manually rebuilds the wiki and deploys it, updating the wiki. This may change since he's planning to do daily automated updates.

**Comment by kenos1** [comment]
top ten things that will never happen

**Comment by DamienVesper** [comment]
boo hoo
