### ISSUE TITLE
Backpacks

### ISSUE THREAD

**Issue by sawq375** [HasangerGames/suroi-wiki#49]
In the backpacks section there's three files called pack_0, pack_2, and pack_3 what do these files represent in the official wiki? Do we need info written for them?

**Comment by kenos1** [comment]
Nothing... They were renamed

**Comment by sawq375** [comment]
ah should i write info for them?

**Comment by kenos1** [comment]
bleh

**Comment by sawq375** [comment]
....wut that mean
