### ISSUE TITLE
Article for Oil tanker has a weird error

### ISSUE THREAD

**Issue by sawq375** [HasangerGames/suroi-wiki#58]
![image](https://github.com/HasangerGames/suroi-wiki/assets/97305445/9a88c618-7409-4c19-aead-8cee397d7184)
 
This error appears when you try to click on the oil tanker buildings in the wiki anybody know what happened here?

**Comment by pythoncat1** [comment]
@kenos1

**Comment by kenos1** [comment]
could be https://github.com/HasangerGames/suroi-wiki/blob/48555874d05f8b6aae80d520f23b4774ec7fc0cf/app/(wiki)/buildings/%5Bitem%5D/page.tsx#L11

**Comment by Compositr** [comment]
Confirmed fixed in the latest version
![image](https://github.com/HasangerGames/suroi-wiki/assets/43405050/57a2d2d9-4476-47b6-98cd-3c18fd41f7ac)
