### ISSUE TITLE
building images not loading in preview

### ISSUE THREAD

**Issue by zedaes** [HasangerGames/suroi-wiki#99]
i was just looking through the wiki and i realized that a bunch of images weren't loading if you were looking at all the buildings, they were  the armory, port, port complex, and invisible container
![Screenshot from 2024-06-25 09-41-51](https://github.com/HasangerGames/suroi-wiki/assets/147769903/71642850-3df5-458f-a11b-16aedcd69721)

idrk if it only isnt working for me or if this has already been reported, but thought i would just point it out :)

**Comment by geodic** [comment]
I think that is intentional... the src of those images points to: https://raw.githubusercontent.com/HasangerGames/suroi/master/client/public/img/game/buildings/undefined.svg
